@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MDc3ZDlhZS01ODUzLTQ5YmYtYWJhYi02ZDY5ZGJkMTAyM2IiLCJpYXQiOjE3MDc0ODg1OTksImV4cCI6MTcwNzQ5MDM5OX0.y8U1_hYQVQoK5ZqdiqZIrK48SJBriRE7sthUIefyNX0

### Check system health
GET {{baseUrl}}/health
Content-Type: application/json

### Create users
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "example"
}

### Get logged-in user data
GET {{baseUrl}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

### Login with credentials
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "example"
}

### Create Two Factor authentication
POST {{baseUrl}}/sessions/two-factor
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### Active Two Factor authentication
PATCH {{baseUrl}}/sessions/two-factor/active
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### Reset Two Factor authentication
PATCH {{baseUrl}}/sessions/two-factor/reset
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### Verify Two Factor authentication
POST {{baseUrl}}/sessions/two-factor/verify
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "token": "937752"
}
