@baseUrl = http://localhost:3333
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MDc3ZDlhZS01ODUzLTQ5YmYtYWJhYi02ZDY5ZGJkMTAyM2IiLCJpYXQiOjE3MDc0MjM0NDcsImV4cCI6MTcwNzQyNTI0N30.aV1Ro5PJjIGNch8gV7DEhSQMmltXZzjs37Y0KBGiALU

### Check system health
GET {{baseUrl}}/health
Content-Type: application/json

### Create users
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "example"
}

### Get logged-in user data
GET {{baseUrl}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json

### Login with credentials
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "example"
}

### Create Two Factor authentication
POST {{baseUrl}}/sessions/two-factor
Authorization: Bearer {{token}}
Content-Type: application/json

{}
